apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - uptimekuma
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
