authentik:
    secret_key: ${authentik_secret_key}
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: ${postgres_password}

ingress:
    enabled: yes
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Authentication"
      gethomepage.dev/description: "Authentication and authorization management."
      gethomepage.dev/group: "Quick Access"
      gethomepage.dev/icon: "authentik.png"
      external-dns.alpha.kubernetes.io/target: ${externaldns_target}
    ingressClassName: "traefik"
    hosts:
      - host: &host "${hostname}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host

postgresql:
    enabled: true
    postgresqlPassword: ${postgres_password}
redis:
    enabled: true