apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets/
    namespace: sealed-secrets
    releaseName: sealed-secrets
    version: 2.16.1
    valuesFile: values.yaml
    includeCRDs: true