# Deploy https://github.com/benphelps/homepage using a helm chart
# and argocd application 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  project: default
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
    # Add our current repo to then inject the custom `values.yaml`
    # file in the helm chart
    # https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
    - repoURL: 'https://github.com/diogosilva30/k3s.dsilva.dev.git'
      targetRevision: main
      ref: current-repo
    # The chart comes from another repository
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 1.2.0
      helm:
        valueFiles:
        # Inject the values reference from this repo
        - $current-repo/manifests/homepage/values.yaml
    
    