# Default values: https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/values.yaml
image:
  repository: ghcr.io/benphelps/homepage
  tag: v0.6.16

# Enable RBAC. RBAC is necessary to use Kubernetes integration
enableRbac: true

serviceAccount:
  # Specify a different service account name
  name: homepage
  # Create service account. Needed when RBAC is enabled.
  create: true

service:
  main:
    ports:
      http:
        port: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

# Enable the ingress to expose Homepage to the network.
ingress:
  main:
    enabled: true
    labels:
      # This label will enable discover of this deployment in Homepage
      gethomepage.dev/enabled: "true"
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      gethomepage.dev/group: "A New Group"
      gethomepage.dev/icon: "homepage.png"
      external-dns.alpha.kubernetes.io/target: "k3s.dsilva.dev"
    ingressClassName: "traefik"
    hosts:
      - host: &host "lab.dsilva.dev"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host

# All the config files for Homepage can be specified under their relevant config block.
config:
  services:
  
  # To use an existing ConfigMap uncomment this line and specify the name
  bookmarks:
    - Git:
        - Github:
            - icon: github-light
              href: https://github.com/diogosilva30
        - GitLab:
            - icon: gitlab
              href: https://gitlab.ubiwhere.com/desilva
  
    - Developer Tools:
        - Homepage Documentation:
            - icon: mdi-bookshelf
              href: https://gethomepage.dev/
        - Self Hosted:
            - abbr: SH
              href: https://github.com/awesome-selfhosted/awesome-selfhosted
       
    - Social:
        - LinkedIn:
            - icon: linkedin
              href: https://www.linkedin.com/in/diogosilva30/

    - Entertainment:
        - YouTube:
            - icon: youtube
              href: https://youtube.com/
        - Netflix:
            - icon: reddit
              href: https://netflix.com/

  
  widgets:
    - greeting:
        text_size: xl
        text: Welcome Diogo Silva!

    # Widget for weather
    - openmeteo:
        label: Weather # optional
        timezone: Europe/Lisbon # optional
        units: metric # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits

    - resources:
        # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
        backend: resources
        expanded: false
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
    # Uncomment to enable Kubernetes integration
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  kubernetes:
    # change mode to 'cluster' to use RBAC service account
    mode: cluster
  docker:
  settings:

persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs

resources:
  requests:
    memory: 10Mi
    cpu: 10m
  limits:
    memory: 200Mi
    cpu: 500m