# values.yaml template file. Has variable placeholders that will be inject by terraform
# Original values.yaml:
# https://github.com/gissilabs/charts/blob/master/vaultwarden/values.yaml

# Kubernetes Ingress
ingress:
  enabled: true
  className: traefik
  host: ${hostname}
  annotations: 
      external-dns.alpha.kubernetes.io/target: "${externaldns_target}"
      # Protect service with SSO
      traefik.ingress.kubernetes.io/router.middlewares: ${traefik_auth_middleware}
      gethomepage.dev/enabled: "true"
      gethomepage.dev/href: "https://${hostname}"
      gethomepage.dev/description: Password management
      gethomepage.dev/group: Services
      gethomepage.dev/icon: bitwarden.png
      gethomepage.dev/name: Vaultwarden


persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  # Persistent Volume storage class
  # storageClass: "-"


replicaCount: 2

