apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    namespace: external-dns
    releaseName: external-dns
    version: 8.3.4
    valuesInline:
      policy: upsert-only
      provider: pihole
      pihole:
        server: 192.168.1.203
