apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: speedtest-tracker
    repo: https://soblivionscall.github.io/charts/
    namespace: speedtest-tracker
    releaseName: speedtest-tracker
    version: 3.0.4
    valuesFile: values.yaml

resources:
  - manifests/ingress.yaml
  
replacements:
  - source:
      kind: Ingress
      name: speedtest-tracker
      fieldPath: metadata.annotations.dns
    targets:
      - select:
          kind: Ingress
          name: speedtest-tracker
        fieldPaths:
          - spec.rules.0.host
        options:
          # This keeps the "speedtest." prefix
          delimiter: "."
          index: 1
