# This Terraform file creates a new Cloudflare tunnel and sets up DNS settings to 
# CNAME to the tunnel target for k3s Ingresses. The tunnel secret is generated using a random ID, 
# and the DNS record is not proxied and not accessible, but serves as a record for auto-created CNAMEs by external-dns.

# Generates a 35-character secret for the tunnel.
resource "random_id" "tunnel_secret" {
  byte_length = 35
}

# The "cloudflare_tunnel" resource creates a new Cloudflare tunnel, 
# using the account ID and tunnel name specified as variables, and the secret 
# generated by the "random_id" resource.
resource "cloudflare_tunnel" "tunnel" {
  account_id = var.cloudflare_account_id
  name       = var.cloudflare_tunnel_name
  secret     = random_id.tunnel_secret.b64_std
}

# DNS settings to CNAME to tunnel target for k3s Ingresses
# Not proxied, not accessible. Just a record for auto-created CNAMEs by external-dns.
resource "cloudflare_record" "tunnel" {
  zone_id = var.cloudflare_zone_id
  name    = "${var.cloudflare_tunnel_name}.${var.cloudflare_dns_zone}"
  value   = "${cloudflare_tunnel.tunnel.id}.cfargotunnel.com"
  type    = "CNAME"
  proxied = false
}
