name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    env:
      AUTH_KEY: ${{ secrets.HEADSCALE_PREAUTH_KEY }}
      HEADSCALE_API_URL: "https://dsilva-headscale-vpn.fly.dev"
      TAILSCALE_UPGRADE: "1"
    steps:
      # Connect to private network with tailscale
      - name: Install tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh
        
      - name: Start Tailscale
        run: sudo tailscale up --auth-key $AUTH_KEY --login-server $HEADSCALE_API_URL --accept-routes

      - name: Tailscale status
        run: tailscale status

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v4
        id: kubectl-install
        with:
           version: 'v1.30.1'
          
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Setup ArgoCD OIDC and RBAC
        run: |
          echo "Setting up ArgoCD OIDC and RBAC"
          kubectl -n argocd patch secret argocd-secret -p '{
            "stringData": {
              "oidc.keycloak.clientSecret": "'$ARGOCD_OIDC_CLIENT_SECRET'"
            }
          }'
          kubectl -n argocd patch cm argocd-cm --type merge --patch "$(cat ./ci-patches/argocd-rbac-patch.yaml)"

          # Restart argoCD pods
          kubectl rollout restart deploy/argocd-server -n argocd
        env:
          ARGOCD_OIDC_CLIENT_SECRET: ${{ secrets.ARGOCD_OIDC_CLIENT_SECRET }}
